apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: pgo
  labels:
    autofail: "true"
    crunchy-pgbadger: "false"
    crunchy-pgha-scope: pgo
    crunchy_collect: "false"
    deployment-name: pgo
    name: pgo
    pg-cluster: pgo
    pg-pod-anti-affinity: ""
    pgo-backrest: "true"
    pgo-version: 4.4.1
    pgouser: admin
  name: pgo
  namespace: pgo
spec:
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: create
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: pgo
    size: 1G
    storageclass: ""
    storagetype: create
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: create
    supplementalgroups: ""
  backrestLimits: {}
  backrestRepoPath: ""
  backrestResources:
    memory: 48Mi
  backrestS3Bucket: ""
  backrestS3Endpoint: ""
  backrestS3Region: ""
  backrestS3URIStyle: ""
  backrestS3VerifyTLS: ""
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos7-12.4-4.4.1
  clustername: pgo
  customconfig: ""
  database: pgo
  exporterport: "9187"
  limits: {}
  name: pgo
  namespace: pgo
  pgBouncer:
    limits: {}
    replicas: 0
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  policies: ""
  port: "5432"
  primarysecretname: pgo-primaryuser-secret
  replicas: "0"
  rootsecretname: pgo-postgres-secret
  shutdown: false
  standby: false
  tablespaceMounts: {}
  tls:
    caSecret: ""
    replicationTLSSecret: ""
    tlsSecret: ""
  tlsOnly: false
  user: hippo
  userlabels:
    crunchy_collect: "false"
    pg-pod-anti-affinity: ""
    pgo-version: 4.4.1
  usersecretname: pgo-hippo-secret
